robot_configurations:
  wheel_model:
    description: "Wheel model"
    values: ["nadia", "moog"]
    default: "moog"
  arm:
    description: "Arm"
    values: [true, false]
    default: true
  laser_model:
    description: "Base laser model"
    values: ["no-laser", "sick-571", "sick-561", "sick-551", "hokuyo"]
    default: sick-571
  courier_rgbd_sensors:
    description: "Whether the base has RGBD sensors or not"
    values: [true, false]
    default: false
  wrist_model:
    description: "Wrist model"
    values: ["wrist-2010", "wrist-2017"]
    default: "wrist-2010"
  end_effector:
    description: "End effector model"
    values: ["pal-gripper", "pal-hey5", "custom", false]
    default: "pal-gripper"
  ft_sensor:
    description: "FT sensor model"
    values: ["schunk-ft", false]
    default: "schunk-ft"
  camera_model:
    description: "Head camera model"
    values: ["orbbec-astra", "orbbec-astra-pro", "asus-xtion", false]
    default: "orbbec-astra"
